language: php

php:
    - 5.5

before_install:
    - sudo chmod 0777 -R app/logs/ app/cache/
    - mysql -e 'create database symfony;'
install:
    - sudo composer install -n --prefer-source

script:
    - phpunit -c app
