fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

base:
    resource: "@BaseBundle/Resources/config/routing.yml"

books:
    resource: "@BooksBundle/Resources/config/routing.yml"

app:
    resource: "@BooksBundle/Controller/BooksController.php"
    type:     annotation
