base:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix:   /

books:
    resource: "@BooksBundle/Resources/config/routing.yml"
    prefix:   /book

app:
    resource: "@BooksBundle/Controller/"
    type:     annotation
