base:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix:   /

books:
    resource: "@BooksBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@BooksBundle/Controller/"
    type:     annotation
