<?php

namespace VienasVienas\Bundle\BooksBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
    public function findQuantity($id)
    {
        $dq = $this->createQueryBuilder('r')
            ->select('r.quantity')
            ->where('r.id = :id')
            ->setParameter('id', $id)
            ->getQuery();

        return $dq->getSingleScalarResult();
    }

    public function selectBooks($id)
    {


        return $dq->getResult();
    }
}
