services:
    make.order:
        class: VienasVienas\Bundle\BaseBundle\Services\OrderService\OrderMake
        arguments: ["@doctrine.orm.entity_manager"]

    order.complete:
        class: VienasVienas\Bundle\BaseBundle\Services\OrderService\OrderComplete
        arguments: ["@doctrine.orm.entity_manager"]

    user.checker:
        class: VienasVienas\Bundle\BaseBundle\Services\OrderService\UserChecker
        arguments: ["@doctrine.orm.entity_manager"]

    order.update:
        class: VienasVienas\Bundle\BaseBundle\Services\OrderService\OrderUpdate
        arguments: ["@doctrine.orm.entity_manager"]

    reservation:
        class: VienasVienas\Bundle\BaseBundle\Services\OrderService\Reservation
        arguments: ["@doctrine.orm.entity_manager"]

    token.generator:
        class: VienasVienas\Bundle\BaseBundle\Services\NotificationService\TokenGenerator

    notification.service:
        class: VienasVienas\Bundle\BaseBundle\Services\NotificationService\NotificationService
        arguments: ["@swiftmailer.mailer"]

    token.checker:
        class: VienasVienas\Bundle\BaseBundle\Services\NotificationService\TokenChecker
        arguments: ["@doctrine.orm.entity_manager"]

    token.setter:
        class: VienasVienas\Bundle\BaseBundle\Services\NotificationService\TokenSetter
        arguments: ["@doctrine.orm.entity_manager", "@notification.service", "@token.generator"]

    security_success_handler:
        class: VienasVienas\Bundle\BaseBundle\Services\AuthSuccessHandler\AuthSuccessHandler
        arguments:  [@router]

    vienasvienas_user.registration.form.type:
        class: VienasVienas\Bundle\BaseBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: base_user_registration }