books_homepage:
    path:     /
    defaults: { _controller: BooksBundle:Default:index }

books_search:
    path:     /search/
    defaults: { _controller: BooksBundle:Search:index }
auto_books_search:
    path:     /search/auto/
    defaults: { _controller: BooksBundle:Search:autoComplete }