books_homepage:
    path:     /
    defaults: { _controller: BooksBundle:Books:index }

books_search:
    path:     /search/
    defaults: { _controller: BooksBundle:Search:index }
auto_books_search:
    path:     /search/auto/
    defaults: { _controller: BooksBundle:Search:autoComplete }

books_categories:
    path:     /category/{categoryId}
    defaults: { _controller: BooksBundle:Category:categoriesAjax }