services:
    book.entity:
        class: VienasVienas\Bundle\BooksBundle\Entity\Book
        public: false

    author.entity:
        class: VienasVienas\Bundle\BooksBundle\Entity\Author

    google.books.finder.parser:
        class: VienasVienas\Bundle\BooksBundle\Services\BookFinderService\GoogleBookFinderParser
        arguments: [@book.entity, @author.entity]

    google.books:
        class: VienasVienas\Bundle\BooksBundle\Services\BookFinderService\GoogleBookFinder
        arguments: [@google.books.finder.parser, %google_key%]

    book.finder:
        class: VienasVienas\Bundle\BooksBundle\Services\BookFinderService\BookFinder
        arguments: [@google.books]

    goodreads.comments:
        class: VienasVienas\Bundle\BooksBundle\Services\BookFinderService\GoodreadsFinder
        arguments: [%goodreads_key%]

    amazon.books.parser:
        class: VienasVienas\Bundle\BooksBundle\Services\BookFinderService\AmazonBookParser
        arguments: [@book.entity, @author.entity]

    amazon.books:
        class: VienasVienas\Bundle\BooksBundle\Services\BookFinderService\AmazonBookFinder
        arguments: [@amazon.books.parser, %amazon_key%, %amazon_secret_key%, %amazon_tag%]

    search.books:
        class: VienasVienas\Bundle\BooksBundle\Services\SearchService\BooksSearch
        arguments: [@fos_elastica.finder.app.book, @book.entity]




