services:
    book.entity:
        class: VienasVienas\Bundle\BooksBundle\Entity\Books
        public: false

    google.books.finder.parser:
        class: VienasVienas\Bundle\BooksBundle\Services\BooksFinderServices\GoogleBookFinderParser
        arguments: [@book.entity]

    google.books:
        class: VienasVienas\Bundle\BooksBundle\Services\BooksFinderServices\GoogleBookFinder
        arguments: [@google.books.finder.parser]

    books.finder:
        class: VienasVienas\Bundle\BooksBundle\Services\BooksFinderServices\BookFinder
        arguments: [@google.books]
