services:
    book.entity:
        class: VienasVienas\Bundle\BooksBundle\Entity\Books
        public: false

    google.books.finder.parser:
        class: VienasVienas\Bundle\BooksBundle\Services\BookFinderService\GoogleBookFinderParser
        arguments: [@book.entity]

    google.books:
        class: VienasVienas\Bundle\BooksBundle\Services\BookFinderService\GoogleBookFinder
        arguments: [@google.books.finder.parser]

    books.finder:
        class: VienasVienas\Bundle\BooksBundle\Services\BookFinderService\BookFinder
        arguments: [@google.books]
    goodreads.comments:
        class: VienasVienas\Bundle\BooksBundle\Services\BookFinderService\GoodreadsFinder
